### ISSUE TITLE
Problem with latest Aurelia

### ISSUE THREAD

**Issue by d13cd2** [donnelljenkins/aurelia-datagrid#16]
Hi 

I'm having trouble getting the grid to work with the latest version of Aurelia.
The error I'm getting is 'Loader must implement loadtemplate(url)'
Any ideas how I would go about getting the grid to work?

Many thanks

**Comment by masteriusz** [comment]
I think I also had this issue recently, doing `jspm update` did the trick. Worth trying :)

**Comment by d13cd2** [comment]
Thanks.  That's got it running.  Now it's not rendering it properly :-/

**Comment by d13cd2** [comment]
I've got it rendering properly now.  :-)
